#!/usr/bin/env node
// scripts/install-wizard.js — Interactive setup wizard.
// Guides a new operator through configuring and deploying the signaling Worker
// on their own domain. Run with: node scripts/install-wizard.js

import { createInterface } from 'readline';
import { writeFileSync, readFileSync, existsSync } from 'fs';
import { execSync, spawnSync } from 'child_process';
import { resolve, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import os from 'os';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WRANGLER_OUT = resolve(ROOT, 'wrangler.jsonc');
const CONFIG_PATH  = resolve(ROOT, 'src', 'config.js');

// ── ANSI helpers ──────────────────────────────────────────────────────────────

const c = {
  reset:  '\x1b[0m',
  bold:   '\x1b[1m',
  dim:    '\x1b[2m',
  green:  '\x1b[32m',
  yellow: '\x1b[33m',
  cyan:   '\x1b[36m',
  red:    '\x1b[31m',
  blue:   '\x1b[34m',
};

const bold    = (s) => `${c.bold}${s}${c.reset}`;
const dim     = (s) => `${c.dim}${s}${c.reset}`;
const green   = (s) => `${c.green}${s}${c.reset}`;
const yellow  = (s) => `${c.yellow}${s}${c.reset}`;
const cyan    = (s) => `${c.cyan}${s}${c.reset}`;
const red     = (s) => `${c.red}${s}${c.reset}`;

function banner() {
  console.log(`
${bold(cyan('╔══════════════════════════════════════════════════════════╗'))}
${bold(cyan('║'))}      ${bold('WebRTC Signaling Worker — Install Wizard')}           ${bold(cyan('║'))}
${bold(cyan('╚══════════════════════════════════════════════════════════╝'))}

This wizard will:
  ${dim('0.')} Check and install prerequisites (wrangler, Atlas CLI)
  ${dim('1.')} Ask for your Worker name and domain (custom or free workers.dev)
  ${dim('2.')} Fetch your MongoDB Atlas connection string
  ${dim('3.')} Optionally configure an auth secret
  ${dim('4.')} Write ${bold('wrangler.jsonc')} for you
  ${dim('5.')} Install npm dependencies
  ${dim('6.')} Push secrets to Cloudflare
  ${dim('7.')} Optionally deploy the Worker

${dim('Press Ctrl+C at any time to abort.')}
`);
}

// ── Readline helpers ──────────────────────────────────────────────────────────

let rl = createInterface({ input: process.stdin, output: process.stdout });

function recreateRl() {
  rl = createInterface({ input: process.stdin, output: process.stdout });
}

function ask(question, defaultValue) {
  return new Promise((resolve) => {
    const suffix = defaultValue !== undefined ? dim(` [${defaultValue}]`) : '';
    rl.question(`${question}${suffix}: `, (answer) => {
      const val = answer.trim();
      resolve(val === '' && defaultValue !== undefined ? defaultValue : val);
    });
  });
}

function askSecret(question) {
  return new Promise((resolve) => {
    process.stdout.write(`${question}: `);
    // Hide input on TTY
    if (process.stdin.isTTY) process.stdin.setRawMode(true);
    let input = '';
    const onData = (chunk) => {
      const char = chunk.toString();
      if (char === '\r' || char === '\n') {
        if (process.stdin.isTTY) process.stdin.setRawMode(false);
        process.stdout.write('\n');
        process.stdin.removeListener('data', onData);
        process.stdin.resume();
        rl.resume();
        resolve(input);
      } else if (char === '\u0003') { // Ctrl+C
        process.exit(0);
      } else if (char === '\u007f' || char === '\b') { // backspace
        if (input.length > 0) input = input.slice(0, -1);
      } else {
        input += char;
        process.stdout.write('*');
      }
    };
    rl.pause();
    process.stdin.resume();
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', onData);
  });
}

async function confirm(question, defaultYes = true) {
  const hint = defaultYes ? dim('Y/n') : dim('y/N');
  const answer = await ask(`${question} ${hint}`);
  if (answer === '') return defaultYes;
  return /^y(es)?$/i.test(answer);
}

// ── Wrangler config builder ───────────────────────────────────────────────────

// ── Read existing wrangler.jsonc ─────────────────────────────────────────────

function readExistingWranglerConfig() {
  if (!existsSync(WRANGLER_OUT)) return {};
  try {
    // Strip // and /* */ comments so JSON.parse can handle jsonc
    const raw = readFileSync(WRANGLER_OUT, 'utf8')
      .replace(/\/\/[^\n]*/g, '')
      .replace(/\/\*[\s\S]*?\*\//g, '');
    const cfg = JSON.parse(raw);
    const name   = cfg.name ?? undefined;
    const domain = cfg.routes?.[0]?.zone_name ?? undefined;
    return { name, domain };
  } catch {
    return {};
  }
}

function buildWranglerConfig(workerName, domain) {
  const routesBlock = domain ? `,
  "routes": [
    {
      "pattern": "${domain}/*",
      "zone_name": "${domain}"
    }
  ]` : `
  // No custom domain — Worker will be reachable at:
  //   https://${workerName}.<account>.workers.dev`;
  return `// wrangler.jsonc — generated by install-wizard.js
{
  "name": "${workerName}",
  "main": "src/index.js",
  "compatibility_date": "2024-09-23",
  "compatibility_flags": ["nodejs_compat_v2"],
  "assets": {
    "directory": "public",
    "run_worker_first": false
  }${routesBlock}
}
`;
}

// ── Platform detection ───────────────────────────────────────────────────────

function detectPlatform() {
  const p = process.platform;
  if (p === 'darwin') return 'mac';
  if (p === 'win32')  return 'win';
  return 'linux';
}

function isCommandAvailable(cmd) {
  try {
    const check = process.platform === 'win32' ? `where ${cmd}` : `command -v ${cmd}`;
    execSync(check, { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function nodeVersion() {
  try {
    const v = process.version.replace('v', '').split('.').map(Number);
    return v[0];
  } catch { return 0; }
}

// Atlas install instructions per platform
function atlasInstallCmd(platform) {
  if (platform === 'mac')   return 'brew install mongodb-atlas-cli';
  if (platform === 'win')   return 'winget install MongoDB.MongoDBAtlasCLI';
  // Linux — download official binary
  return [
    'curl -fsSL https://fastdl.mongodb.org/mongocli/mongodb-atlas-cli_latest_linux_x86_64.tar.gz -o atlas.tar.gz',
    'tar -xzf atlas.tar.gz',
    'sudo mv mongodb-atlas-cli_*/bin/atlas /usr/local/bin/atlas',
    'rm -rf atlas.tar.gz mongodb-atlas-cli_*',
  ].join(' && ');
}

// Wrangler global install (fallback if npx not usable)
function wranglerInstallCmd() {
  return 'npm install -g wrangler';
}

// ── Shell helpers ─────────────────────────────────────────────────────────────

function run(cmd, opts = {}) {
  console.log(dim(`  $ ${cmd}`));
  const result = spawnSync(cmd, { shell: true, stdio: 'inherit', cwd: ROOT, ...opts });
  if (result.status !== 0) {
    throw new Error(`Command failed (exit ${result.status}): ${cmd}`);
  }
}

// For interactive commands that need real terminal stdin (e.g. auth flows).
// Closes readline so the child process gets uncontested stdin, then recreates it.
function runInteractive(cmd) {
  console.log(dim(`  $ ${cmd}`));
  rl.close();
  const result = spawnSync(cmd, { shell: true, stdio: 'inherit', cwd: ROOT });
  recreateRl();
  if (result.status !== 0) {
    throw new Error(`Command failed (exit ${result.status}): ${cmd}`);
  }
}

function runCapture(cmd) {
  return execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trim();
}

function wranglerPutSecret(name, value) {
  // Pass the secret value via stdin so it never appears on the command line.
  const result = spawnSync(
    'npx', ['wrangler', 'secret', 'put', name],
    {
      input: value + '\n',
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'inherit', 'inherit'],
    }
  );
  if (result.status !== 0) {
    throw new Error(`wrangler secret put ${name} failed`);
  }
}

// ── Auth flag patcher ─────────────────────────────────────────────────────────

function enableAuthRequired() {
  const src = readFileSync(CONFIG_PATH, 'utf8');
  const patched = src.replace(
    /AUTH_REQUIRED:\s*false/,
    'AUTH_REQUIRED: true'
  );
  if (patched === src) {
    console.log(yellow('  Warning: could not patch AUTH_REQUIRED in src/config.js — set it manually.'));
    return false;
  }
  writeFileSync(CONFIG_PATH, patched, 'utf8');
  return true;
}

// ── Atlas CLI helpers ────────────────────────────────────────────────────────

function atlasCapture(args) {
  return execSync(`atlas ${args} --output json 2>/dev/null`, { encoding: 'utf8' }).trim();
}

function atlasLoggedIn() {
  try { execSync('atlas auth whoami', { stdio: 'ignore' }); return true; } catch { return false; }
}

// ── Validation helpers ────────────────────────────────────────────────────────

function validateWorkerName(name) {
  if (!name) return 'Worker name is required.';
  if (!/^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(name) && name.length > 1)
    return 'Must be lowercase alphanumeric with hyphens (e.g. my-signaling-worker).';
  return null;
}

function validateDomain(domain) {
  if (!domain) return null; // empty = use workers.dev, that's valid
  if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(domain))
    return 'Enter a bare domain like example.com or signal.myapp.io.';
  return null;
}

function validateMongoUri(uri) {
  if (!uri) return 'MongoDB URI is required.';
  if (!uri.startsWith('mongodb') && !uri.startsWith('mongodb+srv'))
    return 'URI must start with mongodb:// or mongodb+srv://';
  return null;
}

// ── Step runners ──────────────────────────────────────────────────────────────

async function stepCheckPrereqs() {
  console.log(`\n${bold('Step 0 — Prerequisites')}`);
  const platform = detectPlatform();
  console.log(dim(`  Platform: ${process.platform} (${os.arch()}), Node ${process.version}`));

  // Node version
  if (nodeVersion() < 18) {
    console.log(red('  ✗ Node.js 18+ is required. Please upgrade: https://nodejs.org'));
    process.exit(1);
  }
  console.log(green('  ✓ Node.js version OK'));

  // Wrangler — available via npx since it's in devDependencies; just verify npx works
  const hasWrangler = isCommandAvailable('wrangler');
  if (hasWrangler) {
    console.log(green('  ✓ wrangler is installed globally'));
  } else {
    console.log(yellow('  ⚠ wrangler not found globally (will use npx — that\'s fine)'));
    const install = await confirm('    Install wrangler globally now?', false);
    if (install) {
      try { run(wranglerInstallCmd()); console.log(green('  ✓ wrangler installed')); }
      catch (e) { console.log(red(`  ✗ Install failed: ${e.message}`)); }
    } else {
      console.log(dim('  Using npx wrangler throughout.'));
    }
  }

  // Atlas CLI
  const hasAtlas = isCommandAvailable('atlas');
  if (hasAtlas) {
    console.log(green('  ✓ Atlas CLI is installed'));
  } else {
    console.log(yellow('  ⚠ Atlas CLI not found — needed to fetch your MongoDB connection string automatically.'));
    const installCmd = atlasInstallCmd(platform);
    console.log(dim(`  Install command: ${installCmd}`));
    const install = await confirm('    Install Atlas CLI now?', true);
    if (install) {
      try { runInteractive(installCmd); console.log(green('  ✓ Atlas CLI installed')); }
      catch (e) {
        console.log(red(`  ✗ Install failed: ${e.message}`));
        console.log(dim('  You can install it manually and re-run, or paste the URI manually in the next step.'));
      }
    } else {
      console.log(dim('  Skipped — you will be asked to paste the URI manually.'));
    }
  }
}

async function stepWorkerName(existing) {
  console.log(`\n${bold('Step 1 — Worker name')}`);
  if (existing) console.log(dim(`  Current value from wrangler.jsonc: ${bold(existing)}`));
  console.log(dim('  Shown in the Cloudflare dashboard. Must be lowercase, alphanumeric, hyphens allowed.'));
  let name;
  while (true) {
    name = await ask('  Worker name', existing ?? `${basename(ROOT).toLowerCase().replace(/[^a-z0-9]+/g, '-')}-signaling`);
    const err = validateWorkerName(name);
    if (!err) break;
    console.log(red(`  ✗ ${err}`));
  }
  console.log(green(`  ✓ Worker name: ${bold(name)}`));
  return name;
}

async function stepDomain(existing) {
  console.log(`\n${bold('Step 2 — Domain (optional)')}`);
  if (existing) console.log(dim(`  Current value from wrangler.jsonc: ${bold(existing)}`));
  console.log(dim('  The domain you\'ve added to Cloudflare (e.g. signal.myapp.io, myapp.com).'));
  console.log(dim('  Leave blank to use your free workers.dev subdomain instead.'));
  let domain;
  while (true) {
    domain = await ask('  Domain (leave blank for workers.dev)', existing ?? '');
    domain = domain.trim();
    const err = validateDomain(domain);
    if (!err) break;
    console.log(red(`  ✗ ${err}`));
  }
  if (domain) {
    console.log(green(`  ✓ Domain: ${bold(domain)}`));
  } else {
    console.log(green(`  ✓ No custom domain — will use workers.dev subdomain`));
  }
  return domain || null;
}

async function stepMongoDB() {
  console.log(`\n${bold('Step 3 — MongoDB URI')}`);

  // Check if secret is already deployed — if so, offer to skip
  try {
    const list = runCapture('npx wrangler secret list 2>/dev/null');
    if (list.includes('MONGODB_URI')) {
      console.log(green('  ✓ MONGODB_URI is already set as a Worker secret.'));
      const update = await confirm('  Update it?', false);
      if (!update) {
        console.log(dim('  Keeping existing secret.'));
        return null; // caller checks for null and skips push
      }
    }
  } catch { /* wrangler not logged in yet — proceed normally */ }

  const hasAtlas = isCommandAvailable('atlas');

  if (hasAtlas) {
    // Ensure logged in
    if (!atlasLoggedIn()) {
      console.log(yellow('  ⚠ Not logged in to Atlas CLI.'));
      const login = await confirm('  Run atlas auth login now?', true);
      if (login) {
        runInteractive('atlas auth login');
      } else {
        console.log(dim('  Falling back to manual URI entry.'));
        return await askMongoUriManually();
      }
    }
    console.log(green('  ✓ Atlas CLI authenticated'));

    // Pick project
    let projectId, projectName;
    try {
      const projectsJson = atlasCapture('projects list');
      const projects = JSON.parse(projectsJson)?.results ?? JSON.parse(projectsJson);
      if (!projects?.length) throw new Error('No projects found');
      console.log(`\n  ${bold('Projects:')}`);
      projects.forEach((p, i) => console.log(`    ${dim(`${i + 1}.`)} ${p.name} ${dim(`(${p.id})`)}`))
      let idx;
      while (true) {
        const ans = await ask(`  Select project`, '1');
        idx = parseInt(ans, 10) - 1;
        if (idx >= 0 && idx < projects.length) break;
        console.log(red('  ✗ Invalid selection.'));
      }
      projectId   = projects[idx].id;
      projectName = projects[idx].name;
      console.log(green(`  ✓ Project: ${bold(projectName)}`));
    } catch (e) {
      console.log(red(`  ✗ Could not list projects: ${e.message}`));
      return await askMongoUriManually();
    }

    // Pick cluster
    let clusterName;
    try {
      const clustersJson = atlasCapture(`clusters list --projectId ${projectId}`);
      const clusters = JSON.parse(clustersJson)?.results ?? JSON.parse(clustersJson);
      if (!clusters?.length) throw new Error('No clusters found');
      console.log(`\n  ${bold('Clusters:')}`);
      clusters.forEach((c, i) => console.log(`    ${dim(`${i + 1}.`)} ${c.name} ${dim(`(${c.stateName ?? ''})`)}`));
      let idx;
      while (true) {
        const ans = await ask(`  Select cluster`, '1');
        idx = parseInt(ans, 10) - 1;
        if (idx >= 0 && idx < clusters.length) break;
        console.log(red('  ✗ Invalid selection.'));
      }
      clusterName = clusters[idx].name;
      console.log(green(`  ✓ Cluster: ${bold(clusterName)}`));
    } catch (e) {
      console.log(red(`  ✗ Could not list clusters: ${e.message}`));
      return await askMongoUriManually();
    }

    // Get connection string base
    let srvBase;
    try {
      const csJson = atlasCapture(`clusters connectionStrings describe ${clusterName} --projectId ${projectId}`);
      const cs = JSON.parse(csJson);
      srvBase = cs.standardSrv ?? cs.standard ?? cs;
      if (typeof srvBase !== 'string') throw new Error('Unexpected format');
      // strip any embedded credentials placeholder
      srvBase = srvBase.replace(/^mongodb\+srv:\/\/[^@]*@/, 'mongodb+srv://');
      console.log(dim(`  Base SRV: ${srvBase}`));
    } catch (e) {
      console.log(red(`  ✗ Could not fetch connection string: ${e.message}`));
      return await askMongoUriManually();
    }

    // Get DB username and password via Atlas CLI user list
    let dbUser, dbPass;
    try {
      const usersJson = atlasCapture(`dbusers list --projectId ${projectId}`);
      const users = JSON.parse(usersJson)?.results ?? JSON.parse(usersJson);
      if (users?.length) {
        console.log(`\n  ${bold('Database users:')}`);
        users.forEach((u, i) => console.log(`    ${dim(`${i + 1}.`)} ${u.username} ${dim(`(${u.databaseName ?? 'admin'})`)}`));
        console.log(`    ${dim(`${users.length + 1}.`)} Create a new user`);
        let idx;
        while (true) {
          const ans = await ask('  Select user', '1');
          idx = parseInt(ans, 10) - 1;
          if (idx >= 0 && idx <= users.length) break;
          console.log(red('  ✗ Invalid selection.'));
        }
        if (idx < users.length) {
          dbUser = users[idx].username;
          console.log(green(`  ✓ User: ${bold(dbUser)}`));
        }
      }
    } catch (e) {
      console.log(yellow(`  ⚠ Could not list DB users: ${e.message}`));
    }

    if (!dbUser) {
      // Create new user
      dbUser = await ask('  New DB username', 'signaling-user');
      const newPass = await askSecret('  New DB password');
      try {
        runCapture(`atlas dbusers create --username "${dbUser}" --password "${newPass.replace(/"/g, '\\"')}" --role readWriteAnyDatabase --projectId ${projectId} 2>&1`);
        console.log(green(`  ✓ DB user ${bold(dbUser)} created`));
        dbPass = newPass;
      } catch (e) {
        console.log(red(`  ✗ Could not create user: ${e.message}`));
        console.log(dim('  Falling back to manual URI entry.'));
        return await askMongoUriManually();
      }
    }

    if (!dbPass) {
      dbPass = await askSecret(`  Password for ${bold(dbUser)}`);
    }

    const dbName = await ask('  Database name', 'signaling');

    const encodedPass = encodeURIComponent(dbPass);
    const host = srvBase.replace(/^mongodb\+srv:\/\//, '').replace(/\/$/, '');
    const cleanUri = `mongodb+srv://${dbUser}:${encodedPass}@${host}/${dbName}?retryWrites=true&w=majority`;

    console.log(green('  ✓ MongoDB URI constructed'));
    return cleanUri;
  }

  return await askMongoUriManually();
}

async function askMongoUriManually() {
  console.log(dim('  Format: mongodb+srv://user:password@cluster.mongodb.net/dbname'));
  console.log(dim('  This will be stored as a Cloudflare Worker secret (never written to disk).'));
  let uri;
  while (true) {
    uri = await askSecret('  MongoDB URI');
    const err = validateMongoUri(uri);
    if (!err) break;
    console.log(red(`  ✗ ${err}`));
  }
  console.log(green('  ✓ MongoDB URI captured'));
  return uri;
}

async function stepAuth() {
  console.log(`\n${bold('Step 4 — Auth (optional)')}`);
  console.log(dim('  If enabled, register messages must include a valid HMAC-SHA-256 bearer token.'));
  const enable = await confirm('  Enable auth?', false);
  if (!enable) {
    console.log(dim('  Skipping auth setup.'));
    return { enabled: false, secret: null };
  }
  console.log(dim('  Enter the shared secret used to sign/verify tokens (min 16 chars).'));
  let secret;
  while (true) {
    secret = await askSecret('  Auth secret');
    if (secret.length >= 16) break;
    console.log(red('  ✗ Secret must be at least 16 characters.'));
  }
  console.log(green('  ✓ Auth secret captured'));
  return { enabled: true, secret };
}

async function stepWriteConfig(workerName, domain) {
  console.log(`\n${bold('Step 5 — Write wrangler.jsonc')}`);
  if (existsSync(WRANGLER_OUT)) {
    const overwrite = await confirm(`  ${yellow('wrangler.jsonc already exists.')} Overwrite?`, false);
    if (!overwrite) {
      console.log(dim('  Keeping existing wrangler.jsonc.'));
      return false;
    }
  }
  const config = buildWranglerConfig(workerName, domain);
  writeFileSync(WRANGLER_OUT, config, 'utf8');
  console.log(green(`  ✓ Wrote wrangler.jsonc`));
  return true;
}

async function stepInstallDeps() {
  console.log(`\n${bold('Step 6 — Install dependencies')}`);
  const skip = await confirm('  Run npm install?', true);
  if (!skip) { console.log(dim('  Skipped.')); return; }
  try {
    run('npm install');
    console.log(green('  ✓ Dependencies installed'));
  } catch (e) {
    console.log(red(`  ✗ npm install failed: ${e.message}`));
    console.log(dim('  You can run it manually: npm install'));
  }
}

async function stepPushSecrets(mongoUri, authConfig) {
  console.log(`\n${bold('Step 7 — Push secrets to Cloudflare')}`);
  console.log(dim('  Requires: npx wrangler (already in devDependencies)'));
  console.log(dim('  You must be logged in: npx wrangler login'));

  const push = await confirm('  Push secrets now?', true);
  if (!push) {
    console.log(yellow('  Skipped. You can push manually:'));
    console.log(dim('    echo <uri> | npx wrangler secret put MONGODB_URI'));
    if (authConfig.enabled) {
      console.log(dim('    echo <secret> | npx wrangler secret put AUTH_SECRET'));
    }
    return;
  }

  try {
    if (mongoUri) {
      console.log('  Pushing MONGODB_URI…');
      wranglerPutSecret('MONGODB_URI', mongoUri);
      console.log(green('  ✓ MONGODB_URI pushed'));
    } else {
      console.log(dim('  MONGODB_URI unchanged — skipping.'));
    }
  } catch (e) {
    console.log(red(`  ✗ Failed to push MONGODB_URI: ${e.message}`));
    console.log(dim('  If you\'re not logged in, run: npx wrangler login'));
  }

  if (authConfig.enabled) {
    try {
      console.log('  Pushing AUTH_SECRET…');
      wranglerPutSecret('AUTH_SECRET', authConfig.secret);
      console.log(green('  ✓ AUTH_SECRET pushed'));

      console.log('  Patching AUTH_REQUIRED in src/config.js…');
      if (enableAuthRequired()) {
        console.log(green('  ✓ AUTH_REQUIRED set to true in src/config.js'));
      }
    } catch (e) {
      console.log(red(`  ✗ Failed to push AUTH_SECRET: ${e.message}`));
    }
  }
}

async function stepDeploy(workerName) {
  console.log(`\n${bold('Step 8 — Deploy')}`);

  // Check for an existing deployment
  let alreadyDeployed = false;
  try {
    const out = runCapture(`npx wrangler deployments list --name "${workerName}" 2>&1`);
    // deployments list prints a table; if there's at least one row beyond the header it's deployed
    const rows = out.split('\n').filter(l => l.trim() && !l.startsWith('Worker') && !l.startsWith('-') && !l.startsWith('Version'));
    alreadyDeployed = rows.length > 0;
  } catch {
    // wrangler not logged in or worker doesn't exist yet — treat as not deployed
  }

  if (alreadyDeployed) {
    console.log(yellow(`  ⚠ Worker ${bold(workerName)} is already deployed. This will push a new version.`));
  } else {
    console.log(dim(`  No existing deployment found for ${workerName}.`));
  }

  const deploy = await confirm(`  ${alreadyDeployed ? 'Re-deploy now?' : 'Deploy now?'}`, true);
  if (!deploy) {
    console.log(dim('  Skipped. Deploy later with: npm run deploy'));
    return;
  }
  try {
    run('npm run deploy');
    console.log(green('  ✓ Worker deployed'));
  } catch (e) {
    console.log(red(`  ✗ Deploy failed: ${e.message}`));
    console.log(dim('  Check your Cloudflare credentials and zone configuration.'));
  }
}

function summary(workerName, domain, authEnabled) {
  const signalHost = domain ?? `${workerName}.<account>.workers.dev`;
  const scheme = domain ? '' : '  (replace <account> with your Cloudflare account subdomain)';
  console.log(`
${bold(green('══════════════════════════════════════════════════════════'))}
${bold(green('  Setup complete!'))}
${bold(green('══════════════════════════════════════════════════════════'))}

  Worker:  ${bold(workerName)}
  Domain:  ${domain ? bold(domain) : dim('workers.dev (free subdomain)')}${scheme}
  Auth:    ${authEnabled ? bold(green('enabled')) : dim('disabled')}

  ${bold('Useful commands:')}
    ${dim('npm run dev')}      Start local dev server (http://localhost:8787)
    ${dim('npm run deploy')}   Re-deploy the Worker
    ${dim('npm run tail')}     Stream live logs from the deployed Worker

  ${bold('Health check:')}
    ${dim(`curl https://${signalHost}/`)}
    ${dim('→ {"status":"ok","service":"webrtc signaling edge",...}')}

  ${bold('Client signal URL:')}
    ${dim(`wss://${signalHost}/ws`)}
`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  banner();

  await stepCheckPrereqs();

  const existing    = readExistingWranglerConfig();
  const workerName  = await stepWorkerName(existing.name);
  const domain      = await stepDomain(existing.domain);
  const mongoUri   = await stepMongoDB();
  const authConfig = await stepAuth();

  await stepWriteConfig(workerName, domain);
  await stepInstallDeps();
  await stepPushSecrets(mongoUri, authConfig);
  await stepDeploy(workerName);

  summary(workerName, domain, authConfig.enabled);
  rl.close();
}

main().catch((err) => {
  console.error(red(`\nFatal error: ${err.message}`));
  rl.close();
  process.exit(1);
});
